services:
  nginx_red:
    image: nginx
    volumes:
      - ./red:/usr/share/nginx/html:ro
    ports:
      - "81:80"

  nginx_green:
    image: nginx
    volumes:
      - ./green:/usr/share/nginx/html:ro
    ports:
      - "83:80"

  nginx_blue:
    image: nginx
    volumes:
      - ./blue:/usr/share/nginx/html:ro
    ports:
      - "84:80"

  web:
    image: node:18
    working_dir: /usr/src/backend
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - "82:9000"
    command: sh -c "
      chmod +x /usr/src/backend/startup.sh &&
      /usr/src/backend/startup.sh"